---
# code provided under the Creative Commons License: http://creativecommons.org/licenses/by-nc-nd/4.0/
# Author: doatt Site: doatt.com

- name: restartrsyslog
  sudo: yes
  service:
    name: rsyslog
    state: restarted
