---
# code provided under the Creative Commons License: http://creativecommons.org/licenses/by-nc-nd/4.0/
# Author: doatt Site: doatt.com

- name: copy 21-application-loggly.conf
  sudo: yes
  copy:
    src: "{{ fileslocation }}file-application.21-application-loggly.conf"
    dest: /etc/rsyslog.d/21-application-loggly.conf
    mode: 0644
  notify:
    - restartrsyslog
  register: resultingdata
- debug: var=resultingdata
