---
# code provided under the Creative Commons License: http://creativecommons.org/licenses/by-nc-nd/4.0/
# Author: doatt Site: doatt.com

- hosts: {{ hostsnames }}
  gather_facts: False
  roles:
    - common
  tasks:
    - include: "{{ fileslocation }}include-loggly-install.yaml"
